@base = https://localhost:7045

###
# ============================
# USERS
# ============================

# Get all users
GET {{base}}/users

###
# Get user by id
GET {{base}}/users/{{userId}}

###
# Create user
POST {{base}}/users
Content-Type: application/json

{
  "username": "demo_user",
  "email": "demo@example.com",
  "passwordHash": "HASHED_PASSWORD",
  "fullName": "Demo User",
  "phone": "0123456789",
  "roleDesc": "student"
}

###
# Update user
PUT {{base}}/users/{{userId}}
Content-Type: application/json

{
  "fullName": "Updated Demo",
  "phone": "09999999",
  "avatar": "https://img.com/a.png",
  "coverImageUrl": "https://img.com/b.png",
  "isActive": true
}

###
# Delete user
DELETE {{base}}/users/{{userId}}



# ============================
# CENTERS
# ============================

###
# Get all centers
GET {{base}}/centers

###
# Get center detail
GET {{base}}/centers/{{centerId}}

###
# Create center
POST {{base}}/centers
Content-Type: application/json

{
  "centerName": "Center A",
  "centerAddress": "123 Main St",
  "phone": "0909999999",
  "centerEmail": "centerA@gmail.com",
  "managerId": "{{userId}}"
}

###
# Update center
PUT {{base}}/centers/{{centerId}}
Content-Type: application/json

{
  "centerName": "Updated Center",
  "centerAddress": "456 New Road",
  "phone": "0901112222",
  "centerEmail": "new_email@gmail.com",
  "logo": "https://img.com/logo.png",
  "isActive": true
}

###
# Delete center
DELETE {{base}}/centers/{{centerId}}



# ============================
# SUBJECTS
# ============================

###
# Get subjects
GET {{base}}/subjects

###
# Get subject detail
GET {{base}}/subjects/{{subjectId}}

###
# Create subject
POST {{base}}/subjects
Content-Type: application/json

{
  "subjectName": "Mathematics 6",
  "gradeLevel": "Grade 6",
  "centerId": "{{centerId}}"
}

###
# Update subject
PUT {{base}}/subjects/{{subjectId}}
Content-Type: application/json

{
  "subjectName": "Math Level 6 Updated",
  "gradeLevel": "Updated"
}

###
# Delete subject
DELETE {{base}}/subjects/{{subjectId}}



# ============================
# CLASSES
# ============================

###
# Get classes
GET {{base}}/classes

###
# Get class detail
GET {{base}}/classes/{{classId}}

###
# Create class
POST {{base}}/classes
Content-Type: application/json

{
  "className": "Math 6A",
  "subjectId": "{{subjectId}}",
  "teacherId": "{{userId}}",
  "centerId": "{{centerId}}",
  "classAddress": "Room 101",
  "unitPrice": 1200000,
  "totalSessions": 20,
  "startDate": "2025-01-01",
  "endDate": "2025-03-01",
  "scheduleDesc": "Monday - Wednesday 7PM",
  "coverImageUrl": "https://img.com/class.png",
  "classStatus": "not start"
}

###
# Update class
PUT {{base}}/classes/{{classId}}
Content-Type: application/json

{
  "className": "Math 6A - Updated",
  "totalSessions": 24,
  "classStatus": "on progress"
}

###
# Delete class
DELETE {{base}}/classes/{{classId}}
