using LMS.Models.Entities;
using LMS.Services.Interfaces;

namespace LMS.Models.ViewModels.StudentService.Api;

public static class ClassSchedulesApi
{
    public static void MapClassSchedulesApi(this IEndpointRouteBuilder app)
    {
        var g = app.MapGroup("/class-schedules");

        g.MapGet("/", async (ICrudService<ClassSchedule, long> svc) =>
        {
            var items = await svc.ListAsync();

            return Results.Ok(items.Items.Select(s => new ClassScheduleListDto(
                s.ScheduleId,
                s.ClassId,
                s.SessionDate ,
                s.RoomName,
                s.StartTime is null ? null : (s.StartTime.Value),
                s.EndTime is null ? null : (s.EndTime.Value),
                s.SlotOrder,
                s.ScheduleLabel,
                s.ScheduleNote,
                s.SlotId,
                s.RoomId
            )));
        });

        g.MapGet("/{id:long}", async (long id, ICrudService<ClassSchedule, long> svc) =>
        {
            var s = await svc.GetByIdAsync(id);
            if (s is null) return Results.NotFound();

            return Results.Ok(new ClassScheduleDetailDto(
                s.ScheduleId,
                s.ClassId,
                s.SessionDate,
                s.RoomName,
                s.StartTime is null ? null : (s.StartTime.Value),
                s.EndTime is null ? null : (s.EndTime.Value),
                s.SlotOrder,
                s.ScheduleLabel,
                s.ScheduleNote,
                s.SlotId,
                s.RoomId,
                s.BatchId,
                s.IsAutoGenerated,
                s.CreatedAt
            ));
        });

        g.MapPost("/", async (ClassScheduleCreateDto dto, ICrudService<ClassSchedule, long> svc) =>
        {
            var s = new ClassSchedule
            {
                ClassId = dto.ClassId,
                SessionDate = dto.SessionDate,
                SlotId = dto.SlotId,
                RoomId = dto.RoomId,
                ScheduleLabel = dto.ScheduleLabel,
                ScheduleNote = dto.ScheduleNote,
                IsAutoGenerated = dto.IsAutoGenerated
            };

            await svc.CreateAsync(s, true);
            return Results.Created($"/class-schedules/{s.ScheduleId}", s.ScheduleId);
        });

        g.MapPut("/{id:long}", async (long id, ClassScheduleUpdateDto dto, ICrudService<ClassSchedule, long> svc) =>
        {
            var s = await svc.GetByIdAsync(id, asNoTracking: false);
            if (s is null) return Results.NotFound();

            if (dto.SessionDate is not null)
                s.SessionDate = dto.SessionDate.Value;

            s.SlotId = dto.SlotId ?? s.SlotId;
            s.RoomId = dto.RoomId ?? s.RoomId;
            s.ScheduleLabel = dto.ScheduleLabel ?? s.ScheduleLabel;
            s.ScheduleNote = dto.ScheduleNote ?? s.ScheduleNote;

            await svc.UpdateAsync(s, true);
            return Results.NoContent();
        });

        g.MapDelete("/{id:long}", async (long id, ICrudService<ClassSchedule, long> svc) =>
        {
            await svc.DeleteByIdAsync(id, true);
            return Results.NoContent();
        });
    }
}
