// <auto-generated />
using System;
using LMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Migrations
{
    [DbContext(typeof(CenterDbContext))]
    [Migration("20251120080003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Models.Entities.Attendance", b =>
                {
                    b.Property<long>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttendanceId"));

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69261C571FE25E");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("LMS.Models.Entities.AuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E5486487A336F7B");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LMS.Models.Entities.Center", b =>
                {
                    b.Property<Guid>("CenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CenterAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CenterEmail")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Logo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CenterId")
                        .HasName("PK__Centers__398FC7F745A25F02");

                    b.HasIndex("ManagerId");

                    b.ToTable("Centers");
                });

            modelBuilder.Entity("LMS.Models.Entities.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ClassStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ScheduleDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927C0743FBE81");

                    b.HasIndex("CenterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("LMS.Models.Entities.ClassMaterial", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloudObjectKey")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaterialType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaterialId")
                        .HasName("PK__ClassMat__C50610F76C6897A5");

                    b.HasIndex("ClassId");

                    b.HasIndex("ExamId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("ClassMaterials");
                });

            modelBuilder.Entity("LMS.Models.Entities.ClassRegistration", b =>
                {
                    b.Property<long>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RegistrationId"));

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("RegistrationStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RegistrationId")
                        .HasName("PK__ClassReg__6EF588108FFE0997");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassRegistrations");
                });

            modelBuilder.Entity("LMS.Models.Entities.ClassSchedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScheduleId"));

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScheduleLabel")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ScheduleNote")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<byte?>("SlotId")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SlotOrder")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ScheduleId")
                        .HasName("PK__ClassSch__9C8A5B496FFD3435");

                    b.HasIndex("ClassId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SlotId");

                    b.HasIndex(new[] { "BatchId" }, "IX_ClassSched_Batch");

                    b.HasIndex(new[] { "SessionDate", "SlotId", "RoomId" }, "IX_ClassSched_SlotRoom");

                    b.ToTable("ClassSchedules", t =>
                        {
                            t.HasTrigger("trg_ClassSchedules_SyncLegacy");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("LMS.Models.Entities.Exam", b =>
                {
                    b.Property<Guid>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExamDate")
                        .HasColumnType("date");

                    b.Property<string>("ExamDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExamStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ExamType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ExamId")
                        .HasName("PK__Exams__297521C7BF71C2CC");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("LMS.Models.Entities.ExamResult", b =>
                {
                    b.Property<long>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResultId"));

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResultId")
                        .HasName("PK__ExamResu__97690208B563FFED");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("LMS.Models.Entities.Feedback", b =>
                {
                    b.Property<long>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FeedbackId"));

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FbStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool?>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<long?>("RegistrationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDD6D692A1E6");

                    b.HasIndex("ClassId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("LMS.Models.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<Guid?>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("NotiType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12892C69B4");

                    b.HasIndex("CenterId");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LMS.Models.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("BankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("PaidAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long?>("RegistrationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TnxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VnpTxnRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A3867C0C89A");

                    b.HasIndex("ClassId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LMS.Models.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("RoomId")
                        .HasName("PK__Rooms__32863939D1D5D956");

                    b.HasIndex(new[] { "CenterId", "RoomName" }, "UQ_Room_Center")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("LMS.Models.Entities.RoomAvailability", b =>
                {
                    b.Property<long>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AvailabilityId"));

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("AvailabilityId")
                        .HasName("PK__RoomAvai__DA3979B10CF81786");

                    b.HasIndex(new[] { "RoomId", "DayOfWeek", "StartTime", "EndTime" }, "IX_RoomAvail");

                    b.ToTable("RoomAvailabilities");
                });

            modelBuilder.Entity("LMS.Models.Entities.ScheduleBatch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BatchId")
                        .HasName("PK__Schedule__5D55CE584AAE1748");

                    b.ToTable("ScheduleBatches");
                });

            modelBuilder.Entity("LMS.Models.Entities.Subject", b =>
                {
                    b.Property<long>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubjectId"));

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("GradeLevel")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA3A8A4D30879");

                    b.HasIndex("CenterId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("LMS.Models.Entities.TeacherAvailability", b =>
                {
                    b.Property<long>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AvailabilityId"));

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AvailabilityId")
                        .HasName("PK__TeacherA__DA3979B19117FA2C");

                    b.HasIndex(new[] { "TeacherId", "DayOfWeek", "StartTime", "EndTime" }, "IX_TeacherAvail");

                    b.ToTable("TeacherAvailabilities");
                });

            modelBuilder.Entity("LMS.Models.Entities.TimeSlot", b =>
                {
                    b.Property<byte>("SlotId")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("SlotLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte?>("SlotOrder")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotId")
                        .HasName("PK__TimeSlot__0A124AAFF9165456");

                    b.HasIndex(new[] { "SlotOrder" }, "UQ__TimeSlot__F57364B47815BB11")
                        .IsUnique()
                        .HasFilter("[SlotOrder] IS NOT NULL");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("LMS.Models.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Avatar")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FullName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RoleDesc")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C5FAC8AE7");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LMS.Models.Entities.Attendance", b =>
                {
                    b.HasOne("LMS.Models.Entities.ClassSchedule", "Schedule")
                        .WithMany("Attendances")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendances_Schedules");

                    b.HasOne("LMS.Models.Entities.User", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendances_Users");

                    b.Navigation("Schedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("LMS.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Models.Entities.Center", b =>
                {
                    b.HasOne("LMS.Models.Entities.User", "Manager")
                        .WithMany("Centers")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK_Centers_Users");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LMS.Models.Entities.Class", b =>
                {
                    b.HasOne("LMS.Models.Entities.Center", "Center")
                        .WithMany("Classes")
                        .HasForeignKey("CenterId")
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Centers");

                    b.HasOne("LMS.Models.Entities.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Subjects");

                    b.HasOne("LMS.Models.Entities.User", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Users");

                    b.Navigation("Center");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LMS.Models.Entities.ClassMaterial", b =>
                {
                    b.HasOne("LMS.Models.Entities.Class", "Class")
                        .WithMany("ClassMaterials")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassMaterials_Classes");

                    b.HasOne("LMS.Models.Entities.Exam", "Exam")
                        .WithMany("ClassMaterials")
                        .HasForeignKey("ExamId")
                        .HasConstraintName("FK_ClassMaterials_Exams");

                    b.HasOne("LMS.Models.Entities.User", "UploadedByUser")
                        .WithMany("ClassMaterials")
                        .HasForeignKey("UploadedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassMaterials_Users");

                    b.Navigation("Class");

                    b.Navigation("Exam");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("LMS.Models.Entities.ClassRegistration", b =>
                {
                    b.HasOne("LMS.Models.Entities.Class", "Class")
                        .WithMany("ClassRegistrations")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassRegistrations_Classes");

                    b.HasOne("LMS.Models.Entities.User", "Student")
                        .WithMany("ClassRegistrations")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassRegistrations_Users");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.Models.Entities.ClassSchedule", b =>
                {
                    b.HasOne("LMS.Models.Entities.ScheduleBatch", "Batch")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK_ClassSchedules_Batches");

                    b.HasOne("LMS.Models.Entities.Class", "Class")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassSchedules_Classes");

                    b.HasOne("LMS.Models.Entities.Room", "Room")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_ClassSchedules_Rooms");

                    b.HasOne("LMS.Models.Entities.TimeSlot", "Slot")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("SlotId")
                        .HasConstraintName("FK_ClassSchedules_TimeSlots");

                    b.Navigation("Batch");

                    b.Navigation("Class");

                    b.Navigation("Room");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("LMS.Models.Entities.Exam", b =>
                {
                    b.HasOne("LMS.Models.Entities.Class", "Class")
                        .WithMany("Exams")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Classes");

                    b.HasOne("LMS.Models.Entities.User", "Teacher")
                        .WithMany("Exams")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Users");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LMS.Models.Entities.ExamResult", b =>
                {
                    b.HasOne("LMS.Models.Entities.Exam", "Exam")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_Exams");

                    b.HasOne("LMS.Models.Entities.User", "Student")
                        .WithMany("ExamResults")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_Users");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.Models.Entities.Feedback", b =>
                {
                    b.HasOne("LMS.Models.Entities.Class", "Class")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedbacks_Classes");

                    b.HasOne("LMS.Models.Entities.ClassRegistration", "Registration")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_Feedbacks_Registrations");

                    b.HasOne("LMS.Models.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedbacks_Users");

                    b.Navigation("Class");

                    b.Navigation("Registration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Models.Entities.Notification", b =>
                {
                    b.HasOne("LMS.Models.Entities.Center", "Center")
                        .WithMany("Notifications")
                        .HasForeignKey("CenterId")
                        .HasConstraintName("FK_Notifications_Centers");

                    b.HasOne("LMS.Models.Entities.Class", "Class")
                        .WithMany("Notifications")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Notifications_Classes");

                    b.HasOne("LMS.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("Center");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Models.Entities.Payment", b =>
                {
                    b.HasOne("LMS.Models.Entities.Class", "Class")
                        .WithMany("Payments")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Payments_Classes");

                    b.HasOne("LMS.Models.Entities.ClassRegistration", "Registration")
                        .WithMany("Payments")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_Payments_Registrations");

                    b.HasOne("LMS.Models.Entities.User", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Users");

                    b.Navigation("Class");

                    b.Navigation("Registration");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.Models.Entities.Room", b =>
                {
                    b.HasOne("LMS.Models.Entities.Center", "Center")
                        .WithMany("Rooms")
                        .HasForeignKey("CenterId")
                        .IsRequired()
                        .HasConstraintName("FK_Rooms_Centers");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("LMS.Models.Entities.RoomAvailability", b =>
                {
                    b.HasOne("LMS.Models.Entities.Room", "Room")
                        .WithMany("RoomAvailabilities")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_RAv_Rooms");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LMS.Models.Entities.Subject", b =>
                {
                    b.HasOne("LMS.Models.Entities.Center", "Center")
                        .WithMany("Subjects")
                        .HasForeignKey("CenterId")
                        .IsRequired()
                        .HasConstraintName("FK_Subjects_Centers");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("LMS.Models.Entities.TeacherAvailability", b =>
                {
                    b.HasOne("LMS.Models.Entities.User", "Teacher")
                        .WithMany("TeacherAvailabilities")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_TAv_Users");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LMS.Models.Entities.Center", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Notifications");

                    b.Navigation("Rooms");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("LMS.Models.Entities.Class", b =>
                {
                    b.Navigation("ClassMaterials");

                    b.Navigation("ClassRegistrations");

                    b.Navigation("ClassSchedules");

                    b.Navigation("Exams");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LMS.Models.Entities.ClassRegistration", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LMS.Models.Entities.ClassSchedule", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("LMS.Models.Entities.Exam", b =>
                {
                    b.Navigation("ClassMaterials");

                    b.Navigation("ExamResults");
                });

            modelBuilder.Entity("LMS.Models.Entities.Room", b =>
                {
                    b.Navigation("ClassSchedules");

                    b.Navigation("RoomAvailabilities");
                });

            modelBuilder.Entity("LMS.Models.Entities.ScheduleBatch", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("LMS.Models.Entities.Subject", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("LMS.Models.Entities.TimeSlot", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("LMS.Models.Entities.User", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("AuditLogs");

                    b.Navigation("Centers");

                    b.Navigation("ClassMaterials");

                    b.Navigation("ClassRegistrations");

                    b.Navigation("Classes");

                    b.Navigation("ExamResults");

                    b.Navigation("Exams");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("TeacherAvailabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
