namespace LMS.Models.ViewModels.StudentService;

public class Refactor
{
}

public record ClassScheduleListDto(
    long ScheduleId,
    Guid ClassId,
    DateOnly SessionDate,
    string? RoomName,
    TimeOnly? StartTime,
    TimeOnly? EndTime,
    int? SlotOrder,
    string? ScheduleLabel,
    string? ScheduleNote,
    byte? SlotId,
    Guid? RoomId
);


public record ExamListDto(
    Guid ExamId,
    Guid ClassId,
    string Title,
    string? ExamType,
    DateOnly? ExamDate,
    Guid TeacherId
);

public record ExamDetailDto(
    Guid ExamId,
    Guid ClassId,
    string Title,
    string? ExamType,
    DateOnly? ExamDate,
    Guid TeacherId,
    decimal? MaxScore,
    int? DurationMin,
    string? ExamDesc,
    string? ExamStatus
);
public record ExamResultDto(
    long ResultId,
    Guid ExamId,
    Guid StudentId,
    decimal? Score,
    string? Note
);
public record ExamResultCreateDto(
    Guid ExamId,
    Guid StudentId,
    decimal? Score,
    string? Note
);

public record ExamResultUpdateDto(
    decimal? Score,
    string? Note
);



public record ExamCreateDto(
    Guid ClassId,
    string Title,
    string? ExamType,
    DateOnly? ExamDate,
    Guid TeacherId,
    decimal? MaxScore,
    int? DurationMin,
    string? ExamDesc,
    string? ExamStatus
);

public record ExamUpdateDto(
    string? Title,
    string? ExamType,
    DateOnly? ExamDate,
    decimal? MaxScore,
    int? DurationMin,
    string? ExamDesc,
    string? ExamStatus
);


public record ClassScheduleUpdateDto(
    DateOnly? SessionDate,
    byte? SlotId,
    Guid? RoomId,
    string? ScheduleLabel,
    string? ScheduleNote
);

public record ClassScheduleCreateDto(
    Guid ClassId,
    DateOnly SessionDate,
    byte? SlotId,
    Guid? RoomId,
    string? ScheduleLabel,
    string? ScheduleNote,
    bool IsAutoGenerated
);

public record ClassScheduleDetailDto(
    long ScheduleId,
    Guid ClassId,
    DateOnly SessionDate,
    string? RoomName,
    TimeOnly? StartTime,
    TimeOnly? EndTime,
    int? SlotOrder,
    string? ScheduleLabel,
    string? ScheduleNote,
    byte? SlotId,
    Guid? RoomId,
    Guid? BatchId,
    bool IsAutoGenerated,
    DateTime CreatedAt
);




public record UserListDto(
    Guid UserId,
    string Username,
    string Email,
    string? FullName,
    string? Avatar,
    string? RoleDesc,
    bool IsActive
);

public record UserDetailDto(
    Guid UserId,
    string Username,
    string Email,
    string? FullName,
    string? Avatar,
    string? Phone,
    string? RoleDesc,
    bool IsActive,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    string? CoverImageUrl
);

public record UserCreateDto(
    string Username,
    string Email,
    string PasswordHash,
    string? FullName,
    string? Phone,
    string? RoleDesc
);

public record UserUpdateDto(
    string? FullName,
    string? Phone,
    string? Avatar,
    string? CoverImageUrl,
    bool? IsActive
);

public record CenterListDto(
    Guid CenterId,
    string CenterName,
    string? CenterAddress,
    string? Phone,
    bool IsActive,
    string? CenterEmail
);

public record CenterDetailDto(
    Guid CenterId,
    string CenterName,
    string? CenterAddress,
    string? Phone,
    bool IsActive,
    string? CenterEmail,
    string? Logo,
    Guid ManagerId,
    DateTime CreatedAt
);

public record CenterCreateDto(
    string CenterName,
    string? CenterAddress,
    string? Phone,
    string? CenterEmail,
    Guid ManagerId
);

public record CenterUpdateDto(
    string? CenterName,
    string? CenterAddress,
    string? Phone,
    string? CenterEmail,
    string? Logo,
    bool? IsActive
);

public record SubjectListDto(
    long SubjectId,
    string SubjectName,
    string? GradeLevel,
    Guid CenterId
);

public record SubjectDetailDto(
    long SubjectId,
    string SubjectName,
    string? GradeLevel,
    Guid CenterId,
    DateTime CreatedAt
);

public record SubjectCreateDto(
    string SubjectName,
    string? GradeLevel,
    Guid CenterId
);

public record SubjectUpdateDto(
    string? SubjectName,
    string? GradeLevel
);

public record ClassListDto(
    Guid ClassId,
    string ClassName,
    long SubjectId,
    Guid TeacherId,
    Guid CenterId,
    string? ClassStatus
);

public record ClassDetailDto(
    Guid ClassId,
    string ClassName,
    long SubjectId,
    Guid TeacherId,
    string? ClassAddress,
    decimal? UnitPrice,
    int? TotalSessions,
    DateOnly? StartDate,
    DateOnly? EndDate,
    string? ScheduleDesc,
    string? CoverImageUrl,
    DateTime CreatedAt,
    Guid CenterId,
    string? ClassStatus
);

public record ClassCreateDto(
    string ClassName,
    long SubjectId,
    Guid TeacherId,
    Guid CenterId,
    string? ClassAddress,
    decimal? UnitPrice,
    int? TotalSessions,
    DateOnly? StartDate,
    DateOnly? EndDate,
    string? ScheduleDesc,
    string? CoverImageUrl,
    string? ClassStatus
);
public record ClassUpdateDto(
    string? ClassName,
    long? SubjectId,
    Guid? TeacherId,
    string? ClassAddress,
    decimal? UnitPrice,
    int? TotalSessions,
    DateOnly? StartDate,
    DateOnly? EndDate,
    string? ScheduleDesc,
    string? CoverImageUrl,
    string? ClassStatus
);

