using LMS.Data;
using LMS.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace LMS.Pages.Manager;

[Authorize(Policy = "ManagerOnly")]
public class ClassScheduleModel : PageModel
{
    private readonly CenterDbContext _db;

    public ClassScheduleModel(CenterDbContext db)
    {
        _db = db;
    }

    public Class? ClassInfo { get; set; }
    public List<ScheduleViewModel> Schedules { get; set; } = new();
    public List<Room> AvailableRooms { get; set; } = new();
    public List<TimeSlot> AvailableSlots { get; set; } = new();
    public string? SuccessMessage { get; set; }
    public string? ErrorMessage { get; set; }

    [BindProperty]
    public ScheduleInputModel Input { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(Guid id)
    {
        await LoadDataAsync(id);
        
        if (ClassInfo == null)
        {
            return NotFound();
        }

        if (TempData["SuccessMessage"] != null)
            SuccessMessage = TempData["SuccessMessage"]?.ToString();
        if (TempData["ErrorMessage"] != null)
            ErrorMessage = TempData["ErrorMessage"]?.ToString();

        return Page();
    }

    public async Task<IActionResult> OnPostCreateScheduleAsync(Guid id)
    {
        if (!ModelState.IsValid)
        {
            await LoadDataAsync(id);
            return Page();
        }

        try
        {
            var classEntity = await _db.Classes.FindAsync(id);
            if (classEntity == null)
            {
                TempData["ErrorMessage"] = "Không tìm thấy lớp học!";
                return RedirectToPage(new { id });
            }

            // Check for duplicate schedule
            var existingSchedule = await _db.ClassSchedules
                .AnyAsync(s => s.ClassId == id && 
                              s.SessionDate == Input.SessionDate && 
                              s.SlotId == Input.SlotId);
            
            if (existingSchedule)
            {
                TempData["ErrorMessage"] = "Lịch học này đã tồn tại!";
                return RedirectToPage(new { id });
            }

            // Check room availability
            var roomConflict = await _db.ClassSchedules
                .AnyAsync(s => s.RoomId == Input.RoomId && 
                              s.SessionDate == Input.SessionDate && 
                              s.SlotId == Input.SlotId);
            
            if (roomConflict)
            {
                TempData["ErrorMessage"] = "Phòng học đã được sử dụng trong khung giờ này!";
                return RedirectToPage(new { id });
            }

            var timeSlot = await _db.TimeSlots.FindAsync(Input.SlotId);
            var roomName = await _db.Rooms.Where(r => r.RoomId == Input.RoomId).Select(r => r.RoomName).FirstOrDefaultAsync();
            
            var newSchedule = new ClassSchedule
            {
                ClassId = id,
                RoomId = Input.RoomId,
                SlotId = Input.SlotId,
                SessionDate = Input.SessionDate,
                RoomName = roomName,
                StartTime = timeSlot?.StartTime,
                EndTime = timeSlot?.EndTime,
                IsAutoGenerated = false,
                CreatedAt = DateTime.Now
            };

            _db.ClassSchedules.Add(newSchedule);
            await _db.SaveChangesAsync();

            TempData["SuccessMessage"] = "Đã thêm lịch học thành công!";
        }
        catch (Exception ex)
        {
            TempData["ErrorMessage"] = $"Lỗi: {ex.Message}";
        }

        return RedirectToPage(new { id });
    }

    public async Task<IActionResult> OnPostDeleteScheduleAsync(long scheduleId, Guid classId)
    {
        try
        {
            var schedule = await _db.ClassSchedules.FindAsync(scheduleId);
            if (schedule != null)
            {
                // Check if schedule has already started
                var today = DateOnly.FromDateTime(DateTime.Now);
                if (schedule.SessionDate < today)
                {
                    TempData["ErrorMessage"] = "Không thể xóa lịch học đã diễn ra!";
                    return RedirectToPage(new { id = classId });
                }

                _db.ClassSchedules.Remove(schedule);
                await _db.SaveChangesAsync();
                TempData["SuccessMessage"] = "Đã xóa lịch học thành công!";
            }
            else
            {
                TempData["ErrorMessage"] = "Không tìm thấy lịch học!";
            }
        }
        catch (Exception ex)
        {
            TempData["ErrorMessage"] = $"Lỗi: {ex.Message}";
        }

        return RedirectToPage(new { id = classId });
    }

    private async Task LoadDataAsync(Guid classId)
    {
        ClassInfo = await _db.Classes
            .Include(c => c.Subject)
            .Include(c => c.Teacher)
            .FirstOrDefaultAsync(c => c.ClassId == classId);

        if (ClassInfo != null)
        {
            Schedules = await _db.ClassSchedules
                .Include(s => s.Room)
                .Include(s => s.Slot)
                .Where(s => s.ClassId == classId)
                .OrderBy(s => s.SessionDate)
                .ThenBy(s => s.StartTime)
                .Select(s => new ScheduleViewModel
                {
                    ScheduleId = s.ScheduleId,
                    SessionDate = s.SessionDate,
                    RoomName = s.RoomName ?? "N/A",
                    TimeSlotName = s.StartTime.HasValue && s.EndTime.HasValue
                        ? $"{s.StartTime.Value.ToString("HH:mm")} - {s.EndTime.Value.ToString("HH:mm")}" 
                        : "N/A",
                    Status = "scheduled"
                })
                .ToListAsync();

            AvailableRooms = await _db.Rooms.ToListAsync();
            AvailableSlots = await _db.TimeSlots.OrderBy(t => t.StartTime).ToListAsync();
        }
    }

    public class ScheduleViewModel
    {
        public long ScheduleId { get; set; }
        public DateOnly SessionDate { get; set; }
        public string RoomName { get; set; } = "";
        public string TimeSlotName { get; set; } = "";
        public string Status { get; set; } = "";
    }

    public class ScheduleInputModel
    {
        public DateOnly SessionDate { get; set; }
        public Guid RoomId { get; set; }
        public byte SlotId { get; set; }
    }
}
